#!/bin/bash

main() {
    local result=""
    local version=""

    case "$1" in

        chromium-1804 )
            # result=$(wget -qO- \
            result=$(curl -sLN \
                http://archive.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/ \
                | grep -Po -m1 '(?<=href=")[^_]*_([0-9.]+-0ubuntu\d+\.18\.04\.[^_"]*)_[^"]*' \
                | cut -d _ -f 2 \
            )
            ;;

        drawio )
            # result=$(wget -qO- \
            result=$(curl -sLN -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/jgraph/drawio-desktop/releases/latest \
                | grep -m1 "tag_name" \
                | grep -Po '[0-9.]+'
            )
            ;;

        freecad )
            # result=$(wget -qO- \
            result=$(curl -sL \
                https://www.freecad.org/downloads.php \
                | grep -m1 -Po 'href="[^"]+\.AppImage' \
                | grep -Po '/[0-9.]+/' \
                | grep -Po '[0-9.]+'
            )
            ;;

        freecad-appimage )
            # result=$(wget -qO- \
            result=$(curl -sL \
                https://www.freecad.org/downloads.php \
                | grep -m1 -Po 'href="[^"]+\.AppImage' \
                | grep -Po 'FreeCAD_.*'
            )
            ;;

        virtualgl )
            # result=$(wget -qO- \
            result=$(curl -sLN -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/VirtualGL/virtualgl/releases/latest \
                | grep -m1 "tag_name" \
                | grep -Po '[0-9.]+'
            )
            ;;

        * )
            echo "Exiting '${0}' with code '1' because of unknown key '${1}'"
            return 1
            ;;

    esac

    if [[ -n "${result}" ]] ; then

        echo "${result}"
    else
        echo "Exiting '${0}' with code '1' because unable to get version of '$1'"
        return 1
    fi
}

main $@
