### This workflow can be optionally triggered by Docker Hub after pushing an image.
name: dockerhub-post-push
on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        default: '(repo not provided)'
      tag:
        required: true
        default: '(tag not provided)'
      gist:
        required: true
        default: '(gist not provided)'
      readme_context:
        required: true
        default: '(readme context not provided)'
      created:
        required: true
        default: '(created not provided)'
      version_sticker:
        required: true
        default: '(version_sticker not provided)'
      version_sticker_verbose:
        required: true
        default: '(version_sticker_verbose not provided)'
jobs:
  dockerhub-callback:
    runs-on: ubuntu-latest
    steps:
    - name: Report trigger
      shell: bash
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Repo: ${{ github.event.inputs.repo }}"
        echo "Tag: ${{ github.event.inputs.tag }}"
        echo "Gist: ${{ github.event.inputs.gist }}"
        echo "Readme context: ${{ github.event.inputs.readme_context }}"
        echo "Created at: ${{ github.event.inputs.created }}"
        echo "Version sticker: ${{ github.event.inputs.version_sticker }}"
        echo -e "Version sticker verbose:\n${{ github.event.inputs.version_sticker_verbose }}"
  dockerhub-description:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker Hub description
      shell: bash
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        chmod +x .github/workflows/deploy-readme.sh
        sleep 60
        .github/workflows/deploy-readme.sh \
          "${{ github.event.inputs.repo }}" \
          "${{ github.event.inputs.gist }}" \
          "${{ github.event.inputs.readme_context }}" \
          "README-dockerhub.md" \
          "readme-append.template"
